// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALc3pbayiQipwF_Imc1L7BIvNEgz-4v8U',
    appId: '1:800823761065:android:47f1b77c1ad05dee3c71b8',
    messagingSenderId: '800823761065',
    projectId: 'subac-app',
    storageBucket: 'subac-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4owd7tp4GY8RkyznL6eSffLH7nhug280',
    appId: '1:800823761065:ios:b683fe6cc2efcc6a3c71b8',
    messagingSenderId: '800823761065',
    projectId: 'subac-app',
    storageBucket: 'subac-app.appspot.com',
    androidClientId: '800823761065-dktblcf50l8do4ofpgnpbkfrvlidskkn.apps.googleusercontent.com',
    iosClientId: '800823761065-4d1q563hboi6bslkj5snrsu4vepsjir0.apps.googleusercontent.com',
    iosBundleId: 'com.example.subacAppUpdate',
  );
}
